{% set major_minor = "3.8" %}
{% set version = major_minor + ".0" %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}.tar.gz              # [not win]
  fn: cmake-{{ version }}.tar.gz                                                          # [not win]
  sha256: cab99162e648257343a20f61bcd0b287f5e88e36fcb2f1d77959da60b7f35969                # [not win]

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win32-x86.zip       # [win32]
  fn: cmake-{{ version }}-win32-x86.zip                                                   # [win32]
  sha256: 857fca00974ad6ac12fa042373d85ad1288770d4f09fbd99753c822df76b1c6c                # [win32]

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win64-x64.zip       # [win64]
  fn: cmake-{{ version }}-win64-x64.zip                                                   # [win64]
  sha256: 602d6c0bd458291d21414f94ee24f5bb623f3a623409e15601cc80b9922ff6bd                # [win64]

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:             # [unix]
    - toolchain      # [unix]
    - bzip2 1.0.*    # [unix]
    - curl           # [unix]
    - expat          # [unix]
    - jsoncpp        # [unix]
    - libarchive     # [unix]
    - ncurses 5.9*   # [unix]
    - xz 5.2.*       # [unix]
    - zlib 1.2.*     # [unix]
    - libuv          # [unix]
    - rhash          # [unix]
    - gcc            # [unix]

  run:
    - bzip2 1.0.*    # [unix]
    - curl           # [unix]
    - expat          # [unix]
    - jsoncpp        # [unix]
    - libarchive     # [unix]
    - ncurses 5.9*   # [unix]
    - xz 5.2.*       # [unix]
    - zlib 1.2.*     # [unix]
    - libuv          # [unix]
    - rhash          # [unix]
    - vs2013_runtime  # [win]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
